stages:
  - docker
  - checkout
  - test

variables:
  # FIXME: set to master when merged
  BITBAKE_IMAGE: ${CI_REGISTRY_IMAGE}:ci-ci-oe-selftest-bitbake
  BITBAKE_CHECKOUT_IMAGE: ${CI_REGISTRY_IMAGE}:ci-ci-oe-selftest-checkout

include:
  - project: 'olp/edge/ota/connect/client/meta-updater'
    ref: 'ci/oe-selftest'
    file: 'scripts/ci/gitlab/docker.yml'
  - project: 'olp/edge/ota/connect/client/meta-updater'
    ref: 'ci/oe-selftest'
    file: 'scripts/ci/gitlab/checkout.yml'
  - project: 'olp/edge/ota/connect/client/meta-updater'
    ref: 'ci/oe-selftest'
    file: 'scripts/ci/gitlab/tests.yml'

Docker setup:
  extends: .bb_docker_remote

  stage: docker
  except:
    - pushes

Checkout:
  extends: .bb_checkout

  stage: checkout
  variables:
    MANIFEST: rocko
    CURRENT_PROJECT: meta-updater
  except:
    - pushes

Build core-image-minimal:
  extends: .bitbake

  stage: test
  variables:
    TEST_BUILD_DIR: 'build-core-image-minimal'
    BITBAKE_TARGETS: 'core-image-minimal'
  except:
    - pushes
